### PR TITLE
Making Queue non-final

### PR DESCRIPTION
**Pull request by daniel-sc**

### CODE REVIEW

**Comment by chadicus** [comment]
Can you give us a use case as to why you need to extend the Queue?

**Comment by daniel-sc** [comment]
The concrete case is: I'm using the queue with some custom MongoCollection wrapper, which is (sadly) not extending the original MongoCollection. Hence the default constructor fails..

**Comment by gaillard** [comment]
Why can't you use an instance in your wrapper? Has-a relationship

**Comment by daniel-sc** [comment]
Hi @gaillard, the actual use case here is that I cannot even create the instance of `Queue` to wrap it, as my `MongoCollection` is fake and will fail the original constructor - so I'd like to overwrite it. Does that make sense?

**Comment by chrisryan** [comment]
It seems to me that it would make sense to be able to have an implementation of the QueueInterface where you can providue the Mongo collection you want to use rather than the being forced into the collection the queue wants to create.

@chadicus do you have any specific objections?

**Comment by gaillard** [comment]
@chrisryan +1

**Comment by chadicus** [comment]
We have added a new AbstractQueue class which you can extend.  The AbstractQueue is only in the v3 alpha release and not recommended for production use at this time

**Pull request closed without merging**
